Description: "Master CloudFormation Template for the Bucket Rekognition Backfill application."
Parameters:
  DeliveryStreamName:
    Type: String
    Description: Enter the name of the firehose delivery stream
    MinLength: 1
  FunctionCode:
    Type: String
    MinLength: 1
  RoleARN:
    Type: String
  BucketARN:
    Type: String
  Prefix:
    Type: String
  LogStreamName:
    Type: String
  LogGroupName:
    Type: String
  BackupPrefix:
    Type: String
  BackupBucketARN:
    Type: String
  LambdaArn:
    Type: String
  IntervalInSeconds:
    Type: Number
  SizeInMBs:
    Type: Number
  CompressionFormat:
    Type: String
  NumberOfRetries:
    Type: Number
  Enabled:
    Type: String

Resources:
  AWSFirehoseFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: AWSFirehoseFunction
      Handler: index.handler
      Role: !Ref RoleARN
      Description: Custom CFN resource to creates and deletes an AWS Firehose Delivery Stream with an ExtendedS3DestinationConfiguration
      Runtime: nodejs4.3
      Timeout: 300
      Code:
        ZipFile: !Ref FunctionCode

  FirehoseDeliveryStreamResource:
    Type: Custom::FirehoseDeliveryStreamResource
    DependsOn: [ AWSFirehoseFunction ]
    Properties:
      ServiceToken: !GetAtt AWSFirehoseFunction.Arn
      DeliveryStreamName: !Ref DeliveryStreamName
