Description: "Master CloudFormation Template for the Bucket Rekognition Backfill application."
Parameters:
  DeliveryStreamName:
    Type: String
    Description: Enter the name of the firehose delivery stream
    MinLength: 1
  FunctionCode:
    Type: String
    MinLength: 1
  RoleARN:
    Type: String
  BucketARN:
    Type: String
  Prefix:
    Type: String
  LogStreamName:
    Type: String
  LogGroupName:
    Type: String
  LogGroupArn:
    Type: String
  BackupPrefix:
    Type: String
  BackupBucketARN:
    Type: String
  LambdaArn:
    Type: String
  IntervalInSeconds:
    Type: Number
  SizeInMBs:
    Type: Number
  CompressionFormat:
    Type: String
  NumberOfRetries:
    Type: Number
  S3BackupModeEnabled:
    Type: String

Resources:
  AWSFirehoseFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonKinesisFirehoseFullAccess
      Policies:
        -
          PolicyName: policy-awsfirehose-deployment-function
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              -
                Effect: Allow
                Action:
                  - iam:PassRole
                Resource: "*"
  AWSFirehoseFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Join ['-', ['firehose-deployment', !Ref DeliveryStreamName] ]
      Handler: index.handler
      Role: !GetAtt AWSFirehoseFunctionRole.Arn
      Description: "Custom CFN resource to creates and deletes an AWS Firehose Delivery Stream with an ExtendedS3DestinationConfiguration"
      Runtime: nodejs4.3
      Timeout: 300
      Code:
        ZipFile: !Ref FunctionCode

  FirehoseDeliveryStreamResource:
    Type: Custom::FirehoseDeliveryStreamResource
    DependsOn: [ AWSFirehoseFunction ]
    Properties:
      ServiceToken: !GetAtt AWSFirehoseFunction.Arn
      DeliveryStreamName: !Ref DeliveryStreamName
      BucketARN: !Ref BucketARN
      RoleARN: !Ref RoleARN
      IntervalInSeconds: !Ref IntervalInSeconds
      SizeInMBs: !Ref SizeInMBs
      LogGroupName: !Ref LogGroupName
      LogStreamName: !Ref LogStreamName
      CompressionFormat: !Ref CompressionFormat
      Prefix: !Ref Prefix
      LogGroupArn: !Ref LogGroupArn
      BackupBucketARN: !Ref BackupBucketARN
      BackupPrefix: !Ref BackupPrefix
      S3BackupModeEnabled: !Ref S3BackupModeEnabled
      LambdaArn: !Ref LambdaArn
